charts:
  loki:
    namespace: loki
    repo: https://grafana.github.io/helm-charts
    chart: loki-stack
    valuesPath: "/full/path/to/loki/values.yaml"

  kube-state-metrics:
    namespace: kube-system
    repo: https://prometheus-community.github.io/helm-charts
    chart: kube-state-metrics

  cert-manager:
    namespace: cert-manager
    repo: https://charts.jetstack.io
    chart: cert-manager
    valuesPath: "/full/path/to/cert-manager/values.yaml"

  metallb:
    namespace: metallb
    repo: https://metallb.github.io/metallb
    chart: metallb
    valuesPath: "/full/path/to/metallb/values.yaml"

  ingress-nginx:
    namespace: ingress
    repo: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    depends:
      - metallb

  fluent-bit:
    namespace: kube-system
    repo: https://fluent.github.io/helm-charts
    chart: fluent-bit
    valuesPath: "/full/path/to/fluent-bit/values.yaml"
